In [1]:
import pandas as pd

In [2]:
df_gaps = pd.read_csv('mbj_gaps.csv')
df_groups = pd.read_json('group_df_ternary.json')

In [3]:
df_gaps

,Unnamed: 0,formula,material_id,cbm,vbm,is_direct_gap,band_gap
0,0,MgNiSb,mp-15778,6.9273,6.9049,False,0.0224
1,1,PtSbTm,mp-16314,8.0552,7.8826,False,0.1726
2,2,AuHoSn,mp-30390,7.1948,7.1541,False,0.0407
3,3,MgPdSb,mp-10183,6.9887,6.9451,False,0.0436
4,4,BiPdTm,mp-1206744,7.3300,7.3169,False,0.0131
...,...,...,...,...,...,...,...
920,920,O12Sb4Zn2,mp-3188,8.1019,5.7648,False,2.3371
921,921,CoEr7I12,mp-1105583,5.3294,4.6058,False,0.7236
922,922,Cu6Dy6Sb8,mp-1189135,7.5650,7.1285,False,0.4365
923,923,B4Rh10Sc6,mp-542020,9.3566,9.3534,False,0.0032
924,924,Co4O12Sm4,mp-20016,7.9047,5.2792,False,2.6255

In [4]:
mbj_gap_dict = {row.material_id: [row.band_gap, row.is_direct_gap] for _, row in df_gaps.iterrows()}

In [5]:
new_rows = []
for index, row in df_groups.iterrows():
    gaps_hse06 = [mbj_gap_dict.get(material_id) for material_id in row.mp_ids]
    is_valid = [x is not None for x in gaps_hse06]
    outdict = {}
    for key in ['A_elements', 'Compositions', 'X_element', 'mp_ids', 'band_gaps']:
        value = getattr(row, key)
        outdict[key] = [x for mask, x in zip(is_valid, value) if mask is True]
    outdict['gaps_mbj'] = [x for mask, x in zip(is_valid, gaps_hse06) if mask is True]
    if len(outdict['mp_ids']) > 1:
        new_rows.append(outdict)

In [6]:
df_mbj = pd.DataFrame.from_records(new_rows)
df_mbj

,A_elements,Compositions,X_element,mp_ids,band_gaps,gaps_mbj
0,"[[Rh, Zn], [Rh, Zn], [Rh, Zn], [Rh, Zn], [Rh, ...","[Rh2ZnAl, FeRh2Zn, ScRh2Zn, TaRh2Zn, Rh2ZnGe, ...","[Al, Fe, Sc, Ta, Ge, Pa, Ho, Mg, Tm, Pm, In, T...","[mp-866033, mp-977361, mp-867769, mp-865804, m...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[[0.073599999999999, False], [0.04340000000000..."
1,"[[Li, Rh], [Li, Rh], [Li, Rh], [Li, Rh], [Li, ...","[LiRh2Sn, LiRh2Ga, LiRh2Bi, LiNbRh2, LiRh2Si, ...","[Sn, Ga, Bi, Nb, Si, Ge, Fe, Ti, Ta, Ac, Np, A...","[mp-864784, mp-862730, mp-861903, mp-864631, m...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[[0.0874000000000005, False], [0.0260999999999..."
2,"[[In, Li], [In, Li], [In, Li], [In, Li], [In, ...","[Li2DyIn, Li2PmIn, Li2NdIn, Li2MgIn, Li2PrIn, ...","[Dy, Pm, Nd, Mg, Pr, Ho, Sm, Er, Sn, Y, Tm, Pb...","[mp-865580, mp-862930, mp-866181, mp-12128, mp...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[[0.0874999999999994, False], [0.0273999999999..."
3,"[[Cu, O], [Cu, O], [Cu, O], [Cu, O], [Cu, O], ...","[Ho(CuO2)2, Pr(CuO2)2, Sm(CuO2)2, Dy(CuO2)2, T...","[Ho, Pr, Sm, Dy, Tm, Y, Cd, Ca, Gd]","[mp-9421, mp-1101476, mp-9417, mp-9420, mp-754...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3202000000000...","[[0.0186999999999999, False], [0.0120000000000..."
4,"[[C, Co], [C, Co], [C, Co], [C, Co], [C, Co], ...","[TbCoC2, HoCoC2, DyCoC2, PuCoC2, TmCoC2, GdCoC...","[Tb, Ho, Dy, Pu, Tm, Gd, Y, Sm, Pr, Nd]","[mp-5106, mp-9241, mp-3847, mp-999290, mp-1350...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[[0.0003999999999999, True], [0.00750000000000..."
...,...,...,...,...,...,...
265,"[[Mg, Ti], [Mg, Ti]]","[MgTiRh2, MgTiIr2]","[Rh, Ir]","[mp-864919, mp-864908]","[0.0, 0.0131]","[[0.0111000000000007, False], [0.0693999999999..."
266,"[[As, S], [As, S]]","[Cu3AsS4, Ag3AsS4]","[Cu, Ag]","[mp-3345, mp-9538]","[0.0, 0.35760000000000003]","[[0.3705000000000007, True], [1.32559999999999..."
267,"[[N, Zn], [N, Zn]]","[Ca(ZnN)2, Mg(ZnN)2]","[Ca, Mg]","[mp-1029258, mp-1245625]","[0.6376000000000001, 0.0]","[[1.8923999999999996, True], [1.35730000000000..."
268,"[[Ce, Se], [Ce, Se]]","[Ce2SeO2, Ce2SeN2]","[O, N]","[mp-754640, mp-1069558]","[0.0, 0.9476]","[[0.8847000000000005, True], [1.11610000000000..."
269,"[[As, P], [As, P]]","[Ga2AsP, In2AsP]","[Ga, In]","[mp-1224789, mp-1223837]","[0.7805000000000001, 0.0]","[[2.0459000000000005, True], [0.9916, True]]"

In [7]:
def gaps_valid(gaps):
    """Check if the gaps are valid"""
    has_direct = any(entry[1] and entry[0] < 0.8 and entry[0] > 0.1 for entry in gaps)  #  There is a direct but small gap betweem 0.1 and 0.5
    has_low = any(entry[0] < 0.1 for entry in gaps)
    return has_direct and has_low

In [11]:
valid = df_mbj.loc[df_mbj.gaps_mbj.apply(gaps_valid)]
valid

,A_elements,Compositions,X_element,mp_ids,band_gaps,gaps_mbj
3,"[[Cu, O], [Cu, O], [Cu, O], [Cu, O], [Cu, O], ...","[Ho(CuO2)2, Pr(CuO2)2, Sm(CuO2)2, Dy(CuO2)2, T...","[Ho, Pr, Sm, Dy, Tm, Y, Cd, Ca, Gd]","[mp-9421, mp-1101476, mp-9417, mp-9420, mp-754...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3202000000000...","[[0.0186999999999999, False], [0.0120000000000..."
12,"[[Pt, Sb], [Pt, Sb], [Pt, Sb], [Pt, Sb], [Pt, ...","[TmPtSb, YPtSb, TbPtSb, PtMnSb, MgPtSb, ScPtSb...","[Tm, Y, Tb, Mn, Mg, Sc, Er, Lu, Dy, Ho]","[mp-16314, mp-4964, mp-16313, mp-5676, mp-1018...","[0.0, 0.10980000000000001, 0.09680000000000001...","[[0.1725999999999992, False], [0.4715999999999..."
29,"[[Cu, Ge], [Cu, Ge], [Cu, Ge], [Cu, Ge], [Cu, ...","[Ge1Cu2Te3, Cu2GeSe3, Cu2GeS3, Cu2GeSe3, Ge1Cu...","[Te, Se, S, Se, Te, S, S, Te, Se]","[mp-12806, mp-4728, mp-15252, mp-677105, mp-67...","[0.0, 0.0, 0.1111, 0.0, 0.0, 0.0258, 0.0466, 0...","[[0.0194999999999998, False], [0.0378000000000..."
50,"[[Sn, Zn], [Sn, Zn], [Sn, Zn], [Sn, Zn], [Sn, ...","[ZnSnP2, ZnSnAs2, Sb2SnZn, ZnSnN2, ZnSnP2, Sb2...","[P, As, Sb, N, P, Sb, As]","[mp-4175, mp-5190, mp-4756, mp-1029469, mp-121...","[0.7043, 0.0, 0.0, 0.1207, 0.4822, 0.0, 0.0]","[[1.6399999999999997, True], [0.75310000000000..."
73,"[[P, Ru], [P, Ru], [P, Ru]]","[EuRu4P12, CeRu4P12, Nd(RuP3)4]","[Eu, Ce, Nd]","[mp-1188524, mp-10069, mp-1189367]","[0.0, 0.1915, 0.0]","[[0.0058000000000006, False], [0.2932000000000..."
84,"[[Cu, Se], [Cu, Se], [Cu, Se], [Cu, Se]]","[CuInSe2, CuAlSe2, CuGaSe2, CuInSe2]","[In, Al, Ga, In]","[mp-22811, mp-8016, mp-4840, mp-1223971]","[0.0, 0.8922, 0.0398, 0.0]","[[0.4024999999999998, True], [1.8677, True], [..."
99,"[[Ca, O], [Ca, O], [Ca, O], [Ca, O], [Ca, O]]","[Ca3SnO, Ca3PbO, Ca3SiO, Ca3SiO, Ca3GeO]","[Sn, Pb, Si, Si, Ge]","[mp-29241, mp-20273, mp-1205330, mp-1183521, m...","[0.0, 0.0, 0.056600000000000004, 0.07, 0.0]","[[0.0259999999999998, False], [0.0102000000000..."
119,"[[Cu, Se], [Cu, Se], [Cu, Se], [Cu, Se]]","[Cu3AsSe4, Cu3SbSe4, Cu3VSe4, Cu3PSe4]","[As, Sb, V, P]","[mp-675626, mp-9814, mp-21855, mp-5756]","[0.0, 0.0, 0.8164, 0.0]","[[0.0309000000000008, False], [0.0023999999999..."
128,"[[As, S], [As, S]]","[TmAsS, SmAsS]","[Tm, Sm]","[mp-1102079, mp-1102762]","[0.0, 0.0256]","[[0.0801000000000007, False], [0.3284000000000..."
129,"[[As, S], [As, S], [As, S]]","[PrAsS, CeAsS, NdAsS]","[Pr, Ce, Nd]","[mp-1101752, mp-1095675, mp-1101764]","[0.0095, 0.0, 0.0]","[[0.3544999999999998, True], [0.0, False], [0...."
218,"[[Pb, Sr], [Pb, Sr]]","[SrMgPb, CaSrPb]","[Mg, Ca]","[mp-1103314, mp-21166]","[0.0, 0.26780000000000004]","[[0.0145999999999997, False], [0.6787000000000..."
226,"[[Ba, Si], [Ba, Si]]","[BaMgSi, BaCaSi]","[Mg, Ca]","[mp-9934, mp-16253]","[0.0, 0.1767]","[[0.0, False], [0.4676, True]]"
251,"[[Pt, Tb], [Pt, Tb]]","[TbPtSb, TbPtBi]","[Sb, Bi]","[mp-16313, mp-1206989]","[0.09680000000000001, 0.0]","[[0.3806000000000002, True], [0.04759999999999..."
253,"[[Pt, Y], [Pt, Y]]","[YPtSb, YBiPt]","[Sb, Bi]","[mp-4964, mp-1206679]","[0.10980000000000001, 0.0]","[[0.4715999999999996, True], [0.05149999999999..."
254,"[[Dy, Pt], [Dy, Pt]]","[DyPtBi, DyPtSb]","[Bi, Sb]","[mp-30453, mp-16327]","[0.0, 0.049300000000000004]","[[0.0445000000000002, False], [0.3376000000000..."

In [37]:
valid.loc[99].gaps_mbj

[[0.0259999999999998, False],
 [0.0102000000000002, False],
 [0.4670999999999994, True],
 [0.4173, True],
 [0.3526999999999995, True]]

In [42]:
combinations = []
for key, row in valid.iterrows():
    mbj_gaps = row.gaps_mbj
    for i in range(len(row.Compositions)):
        for j in range(i, len(row.Compositions)):
            if (mbj_gaps[i][0] < 0.1 and mbj_gaps[j][0] < 0.6 and mbj_gaps[j][0] > 0.1 ) or (mbj_gaps[j][0] < 0.1 and mbj_gaps[i][0] < 0.6 and mbj_gaps[i][0] > 0.1 ):
                if not mbj_gaps[i][1]:
                    j, i = i, j
                data = {'comp_a': row.Compositions[i], 
                        'comp_b': row.Compositions[j],
                        'gap_a': mbj_gaps[i][0],
                        'gap_b': mbj_gaps[j][0],
                        'mp_id_a': row.mp_ids[i],
                        'mp_id_b': row.mp_ids[j],
                        'gap_direct_a':mbj_gaps[i][1],
                        'gap_direct_b': mbj_gaps[j][1],
                       }
                if data['comp_a'] == data['comp_b']:
                    continue
                combinations.append(data)

In [43]:
pairs = pd.DataFrame.from_dict(combinations)
pairs = pairs[pairs.gap_direct_a | pairs.gap_direct_b]

In [45]:
pairs

,comp_a,comp_b,gap_a,gap_b,mp_id_a,mp_id_b,gap_direct_a,gap_direct_b
2,YPtSb,PtMnSb,0.4716,0.0052,mp-4964,mp-5676,True,False
3,YPtSb,MgPtSb,0.4716,0.0375,mp-4964,mp-10184,True,False
4,TbPtSb,PtMnSb,0.3806,0.0052,mp-16313,mp-5676,True,False
5,TbPtSb,MgPtSb,0.3806,0.0375,mp-16313,mp-10184,True,False
8,Cu2GeS3,Ge1Cu2Te3,0.5936,0.0195,mp-15252,mp-12806,True,False
9,Cu2GeS3,Cu2GeSe3,0.5936,0.0462,mp-15252,mp-677105,True,False
10,Cu2GeS3,Ge1Cu2Te3,0.5936,0.0048,mp-15252,mp-674953,True,False
11,Cu2GeS3,Ge1Cu2Te3,0.5936,0.0317,mp-15252,mp-1225891,True,False
12,Cu2GeS3,Cu2GeSe3,0.5936,0.0378,mp-15252,mp-4728,True,False
13,Cu2GeS3,Cu2GeSe3,0.5936,0.0462,mp-15252,mp-677105,True,False
14,Cu2GeS3,Ge1Cu2Te3,0.5936,0.0048,mp-15252,mp-674953,True,False
15,Cu2GeS3,Ge1Cu2Te3,0.5936,0.0317,mp-15252,mp-1225891,True,False
16,Cu2GeS3,Cu2GeSe3,0.5936,0.0462,mp-15252,mp-677105,True,False
17,Cu2GeS3,Ge1Cu2Te3,0.5936,0.0048,mp-15252,mp-674953,True,False
18,Cu2GeS3,Ge1Cu2Te3,0.5936,0.0317,mp-15252,mp-1225891,True,False
19,Cu2GeS3,Cu2GeSe3,0.2872,0.0462,mp-1225871,mp-677105,True,False
20,Cu2GeS3,Ge1Cu2Te3,0.2872,0.0317,mp-1225871,mp-1225891,True,False
21,Cu2GeS3,Ge1Cu2Te3,0.2872,0.0048,mp-1225871,mp-674953,True,False
22,Cu2GeS3,Ge1Cu2Te3,0.2872,0.0317,mp-1225871,mp-1225891,True,False
23,Cu2GeS3,Ge1Cu2Te3,0.2872,0.0317,mp-1225871,mp-1225891,True,False
24,Cu2GeS3,Ge1Cu2Te3,0.2872,0.0317,mp-1225871,mp-1225891,True,False
26,ZnSnAs2,Sb2SnZn,0.4807,0.0931,mp-1215434,mp-1215452,True,False
27,CeRu4P12,EuRu4P12,0.2932,0.0058,mp-10069,mp-1188524,True,False
28,CeRu4P12,Nd(RuP3)4,0.2932,0.0707,mp-10069,mp-1189367,True,False
29,CeRu4P12,Nd(RuP3)4,0.2932,0.0707,mp-10069,mp-1189367,True,False
30,Ca3SiO,Ca3SnO,0.4671,0.0260,mp-1205330,mp-29241,True,False
31,Ca3SiO,Ca3PbO,0.4671,0.0102,mp-1205330,mp-20273,True,False
32,SmAsS,TmAsS,0.3284,0.0801,mp-1102762,mp-1102079,True,False
33,PrAsS,CeAsS,0.3545,0.0000,mp-1101752,mp-1095675,True,False
34,NdAsS,CeAsS,0.3437,0.0000,mp-1101764,mp-1095675,True,False
35,BaCaSi,BaMgSi,0.4676,0.0000,mp-16253,mp-9934,True,False
36,TbPtSb,TbPtBi,0.3806,0.0476,mp-16313,mp-1206989,True,False
37,YPtSb,YBiPt,0.4716,0.0515,mp-4964,mp-1206679,True,False
38,DyPtSb,DyPtBi,0.3376,0.0445,mp-16327,mp-30453,True,False

,comp_a,comp_b,gap_a,gap_b,mp_id_a,mp_id_b,gap_direct_a,gap_direct_b
2,YPtSb,PtMnSb,0.4716,0.0052,mp-4964,mp-5676,True,False
3,YPtSb,MgPtSb,0.4716,0.0375,mp-4964,mp-10184,True,False
4,TbPtSb,PtMnSb,0.3806,0.0052,mp-16313,mp-5676,True,False
5,TbPtSb,MgPtSb,0.3806,0.0375,mp-16313,mp-10184,True,False
8,PtMnSb,DyPtSb,0.0052,0.3376,mp-5676,mp-16327,False,True
9,PtMnSb,HoPtSb,0.0052,0.2990,mp-5676,mp-16376,False,True
12,MgPtSb,DyPtSb,0.0375,0.3376,mp-10184,mp-16327,False,True
13,MgPtSb,HoPtSb,0.0375,0.2990,mp-10184,mp-16376,False,True
14,Ge1Cu2Te3,Cu2GeS3,0.0195,0.5936,mp-12806,mp-15252,False,True
15,Ge1Cu2Te3,Cu2GeS3,0.0195,0.2872,mp-12806,mp-1225871,False,True
17,Cu2GeSe3,Cu2GeS3,0.0378,0.5936,mp-4728,mp-15252,False,True
18,Cu2GeSe3,Cu2GeS3,0.0378,0.2872,mp-4728,mp-1225871,False,True
19,Cu2GeS3,Cu2GeSe3,0.5936,0.0462,mp-15252,mp-677105,True,False
20,Cu2GeS3,Ge1Cu2Te3,0.5936,0.0048,mp-15252,mp-674953,True,False
21,Cu2GeS3,Ge1Cu2Te3,0.5936,0.0317,mp-15252,mp-1225891,True,False
22,Cu2GeSe3,Cu2GeS3,0.0462,0.2872,mp-677105,mp-1225871,False,True
23,Ge1Cu2Te3,Cu2GeS3,0.0048,0.2872,mp-674953,mp-1225871,False,True
26,Cu2GeS3,Ge1Cu2Te3,0.2872,0.0317,mp-1225871,mp-1225891,True,False
28,Sb2SnZn,ZnSnAs2,0.0931,0.4807,mp-1215452,mp-1215434,False,True
29,EuRu4P12,CeRu4P12,0.0058,0.2932,mp-1188524,mp-10069,False,True
30,CeRu4P12,Nd(RuP3)4,0.2932,0.0707,mp-10069,mp-1189367,True,False
31,Ca3SnO,Ca3SiO,0.0260,0.4671,mp-29241,mp-1205330,False,True
32,Ca3SnO,Ca3SiO,0.0260,0.4173,mp-29241,mp-1183521,False,True
33,Ca3SnO,Ca3GeO,0.0260,0.3527,mp-29241,mp-9721,False,True
34,Ca3PbO,Ca3SiO,0.0102,0.4671,mp-20273,mp-1205330,False,True
35,Ca3PbO,Ca3SiO,0.0102,0.4173,mp-20273,mp-1183521,False,True
36,Ca3PbO,Ca3GeO,0.0102,0.3527,mp-20273,mp-9721,False,True
37,TmAsS,SmAsS,0.0801,0.3284,mp-1102079,mp-1102762,False,True
38,PrAsS,CeAsS,0.3545,0.0000,mp-1101752,mp-1095675,True,False
39,CeAsS,NdAsS,0.0000,0.3437,mp-1095675,mp-1101764,False,True
40,BaMgSi,BaCaSi,0.0000,0.4676,mp-9934,mp-16253,False,True
41,TbPtSb,TbPtBi,0.3806,0.0476,mp-16313,mp-1206989,True,False
42,YPtSb,YBiPt,0.4716,0.0515,mp-4964,mp-1206679,True,False
43,DyPtBi,DyPtSb,0.0445,0.3376,mp-30453,mp-16327,False,True