In [27]:
import pandas as pd

In [28]:
df_gaps = pd.read_csv('mbj_gaps_tenary_2025_0425_pmg_info.csv')
df_groups = pd.read_json('ternary-group-df.json')

df_groups = df_groups.rename({'Compositions': 'compositions'}, axis=1)

In [29]:
df_gaps

,Unnamed: 0,formula,material_id,direct,transition,band_gap
0,0,Cu2Lu2Sb4,mp-1080126,False,NaN,0.0000
1,514,C6Al6Gd2,mp-1104806,False,NaN,0.0000
2,515,Ca6Fe2N6,mp-1029659,False,NaN,0.0000
3,516,Eu2Ga4Te8,mp-1103807,False,NaN,0.0000
4,517,Cu4Dy2O8,mp-9420,False,NaN,0.0000
...,...,...,...,...,...,...
922,46,As2NiO6,mp-19384,False,H-\Gamma,3.8066
923,882,F6MgNi,mp-1409292,False,L-F,3.8860
924,525,Co4Mg2O8,mp-756442,False,"X-(0.469,0.000,0.469)",3.9243
925,890,Ca2Cu2F8,mp-12266,False,Z-X,3.9367
926,377,CoLiO2,mp-22526,False,"Z-(0.000,0.241,0.000)",4.1974

In [30]:
mbj_gap_dict = {row.material_id: [row.band_gap, row.direct] for _, row in df_gaps.iterrows()}

In [31]:
new_rows = []
for index, row in df_groups.iterrows():
    gaps_hse06 = [mbj_gap_dict.get(material_id) for material_id in row.mp_ids]
    is_valid = [x is not None for x in gaps_hse06]
    outdict = {}
    for key in ['A_elements', 'compositions', 'X_element', 'mp_ids', 'band_gaps']:
        value = getattr(row, key)
        outdict[key] = [x for mask, x in zip(is_valid, value) if mask is True]
    outdict['gaps_mbj'] = [x for mask, x in zip(is_valid, gaps_hse06) if mask is True]
    if len(outdict['mp_ids']) > 1:
        new_rows.append(outdict)

In [32]:
df_mbj = pd.DataFrame.from_records(new_rows)
df_mbj

,A_elements,compositions,X_element,mp_ids,band_gaps,gaps_mbj
0,"[[Rh, Zn], [Rh, Zn], [Rh, Zn], [Rh, Zn], [Rh, ...","[Rh2ZnAl, FeRh2Zn, ScRh2Zn, TaRh2Zn, Rh2ZnGe, ...","[Al, Fe, Sc, Ta, Ge, Pa, Ho, Mg, Tm, Pm, In, T...","[mp-866033, mp-977361, mp-867769, mp-865804, m...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[[0.0, False], [0.0, False], [0.0, False], [0...."
1,"[[Li, Rh], [Li, Rh], [Li, Rh], [Li, Rh], [Li, ...","[LiRh2Sn, LiRh2Ga, LiRh2Bi, LiNbRh2, LiRh2Si, ...","[Sn, Ga, Bi, Nb, Si, Ge, Fe, Ti, Ta, Ac, Np, A...","[mp-864784, mp-862730, mp-861903, mp-864631, m...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[[0.0, False], [0.0, False], [0.0, False], [0...."
2,"[[In, Li], [In, Li], [In, Li], [In, Li], [In, ...","[Li2DyIn, Li2PmIn, Li2NdIn, Li2MgIn, Li2PrIn, ...","[Dy, Pm, Nd, Mg, Pr, Ho, Sm, Er, Sn, Y, Tm, Pb...","[mp-865580, mp-862930, mp-866181, mp-12128, mp...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[[0.0, False], [0.0, False], [0.0, False], [0...."
3,"[[Cu, O], [Cu, O], [Cu, O], [Cu, O], [Cu, O], ...","[Ho(CuO2)2, Pr(CuO2)2, Sm(CuO2)2, Dy(CuO2)2, T...","[Ho, Pr, Sm, Dy, Tm, Y, Cd, Ca, Gd]","[mp-9421, mp-1101476, mp-9417, mp-9420, mp-754...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3202000000000...","[[0.0, False], [0.0, False], [0.65289999999999..."
4,"[[C, Co], [C, Co], [C, Co], [C, Co], [C, Co], ...","[TbCoC2, HoCoC2, DyCoC2, PuCoC2, TmCoC2, GdCoC...","[Tb, Ho, Dy, Pu, Tm, Gd, Y, Sm, Pr, Nd]","[mp-5106, mp-9241, mp-3847, mp-999290, mp-1350...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[[0.0, False], [0.0, False], [0.0, False], [0...."
...,...,...,...,...,...,...
265,"[[Mg, Ti], [Mg, Ti]]","[MgTiRh2, MgTiIr2]","[Rh, Ir]","[mp-864919, mp-864908]","[0.0, 0.0131]","[[0.0, False], [0.0, False]]"
266,"[[As, S], [As, S]]","[Cu3AsS4, Ag3AsS4]","[Cu, Ag]","[mp-3345, mp-9538]","[0.0, 0.35760000000000003]","[[0.3705000000000007, True], [1.32559999999999..."
267,"[[N, Zn], [N, Zn]]","[Ca(ZnN)2, Mg(ZnN)2]","[Ca, Mg]","[mp-1029258, mp-1245625]","[0.6376000000000001, 0.0]","[[1.8923999999999996, True], [1.35730000000000..."
268,"[[Ce, Se], [Ce, Se]]","[Ce2SeO2, Ce2SeN2]","[O, N]","[mp-754640, mp-1069558]","[0.0, 0.9476]","[[0.8847000000000005, True], [1.11610000000000..."
269,"[[As, P], [As, P]]","[Ga2AsP, In2AsP]","[Ga, In]","[mp-1224789, mp-1223837]","[0.7805000000000001, 0.0]","[[2.0459000000000005, True], [0.9916, True]]"

In [33]:
def gaps_valid(gaps):
    """Check if the gaps are valid"""
    has_direct = any(entry[0] < 1.5 and entry[0] > 0.15 for entry in gaps)  #  There is a direct but small gap betweem 0.1 and 0.5
    has_low = any(entry[0] < 0.15 for entry in gaps)
    return has_direct and has_low

In [34]:
valid = df_mbj.loc[df_mbj.gaps_mbj.apply(gaps_valid)]
valid

,A_elements,compositions,X_element,mp_ids,band_gaps,gaps_mbj
3,"[[Cu, O], [Cu, O], [Cu, O], [Cu, O], [Cu, O], ...","[Ho(CuO2)2, Pr(CuO2)2, Sm(CuO2)2, Dy(CuO2)2, T...","[Ho, Pr, Sm, Dy, Tm, Y, Cd, Ca, Gd]","[mp-9421, mp-1101476, mp-9417, mp-9420, mp-754...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3202000000000...","[[0.0, False], [0.0, False], [0.65289999999999..."
5,"[[Bi, Pd], [Bi, Pd], [Bi, Pd], [Bi, Pd], [Bi, ...","[CePdBi, TmPdBi, YPdBi, PrPdBi, HoPdBi, TbPdBi...","[Ce, Tm, Y, Pr, Ho, Tb, Sm, Dy, Nd]","[mp-604453, mp-1206744, mp-1008624, mp-1206720...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1051]","[[0.4576000000000002, False], [0.0, False], [0..."
7,"[[Ru, Zr], [Ru, Zr], [Ru, Zr], [Ru, Zr], [Ru, ...","[ScZrRu2, ZrRu2Ge, ZrRu2Ga, Ru2ZrAl, ZrRu2Si, ...","[Sc, Ge, Ga, Al, Si, Tm, Sn, Ho, Dy, Hf]","[mp-1188014, mp-977443, mp-1188059, mp-977436,...","[0.0, 0.0, 0.0, 0.0, 0.2353, 0.0, 0.0, 0.0, 0....","[[0.0, False], [0.0, False], [0.0, False], [0...."
10,"[[B, Er], [B, Er], [B, Er], [B, Er], [B, Er], ...","[ErMoB4, ErCrB4, ErWB4, ErAlB4, ErRhB4, ErCoB4...","[Mo, Cr, W, Al, Rh, Co, V, Fe, Ru, Re]","[mp-1190816, mp-985700, mp-1192093, mp-1213107...","[0.5881000000000001, 0.16110000000000002, 0.59...","[[0.4247999999999994, False], [0.0, False], [0..."
11,"[[Ru, Si], [Ru, Si], [Ru, Si], [Ru, Si], [Ru, ...","[BeRu2Si, Ru2MnSi, Ru2AlSi, ZrRu2Si, LiRu2Si, ...","[Be, Mn, Al, Zr, Li, V, Ti, Hf, Ga, Fe]","[mp-867835, mp-864966, mp-862778, mp-1183042, ...","[0.0, 0.0, 0.0, 0.2353, 0.0, 0.0, 0.0, 0.1695,...","[[0.0, False], [0.0, False], [0.0, False], [0...."
...,...,...,...,...,...,...
254,"[[Dy, Pt], [Dy, Pt]]","[DyPtBi, DyPtSb]","[Bi, Sb]","[mp-30453, mp-16327]","[0.0, 0.049300000000000004]","[[0.0, False], [0.3376000000000001, True]]"
256,"[[Ge, Li], [Ge, Li]]","[LiAlGe, LiInGe]","[Al, In]","[mp-5920, mp-16343]","[0.052700000000000004, 0.0]","[[0.4649999999999998, False], [0.0, False]]"
259,"[[Ca, Sb], [Ca, Sb]]","[CaLiSb, CaAgSb]","[Li, Ag]","[mp-16264, mp-11214]","[0.6443, 0.0]","[[0.9957000000000004, True], [0.0, False]]"
260,"[[Pt, Sb], [Pt, Sb]]","[PtSbS, PtSiSb]","[S, Si]","[mp-1102850, mp-11152]","[0.0, 0.2086]","[[0.0, False], [0.373800000000001, False]]"
261,"[[Bi, F], [Bi, F]]","[ZnBiF6, CaBiF6]","[Zn, Ca]","[mp-1446593, mp-1387328]","[0.0, 0.037200000000000004]","[[0.0, False], [1.1002, False]]"

In [35]:
combinations = []
for key, row in valid.iterrows():
    mbj_gaps = row.gaps_mbj
    for i in range(len(row.compositions)):
        for j in range(i, len(row.compositions)):
            if any([mbj_gaps[i][0] < 0.3, mbj_gaps[j][0] < 0.3]) and \
            any([mbj_gaps[i][0] > 0.2, mbj_gaps[j][0] > 0.2]) and \
            not any([mbj_gaps[i][0] > 0.8, mbj_gaps[j][0] > 0.8]):
            # if (mbj_gaps[i][0] < 0.1 and mbj_gaps[j][0] < 0.6 and mbj_gaps[j][0] > 0.1 ) or (mbj_gaps[j][0] < 0.1 and mbj_gaps[i][0] < 0.6 and mbj_gaps[i][0] > 0.1 ):
                # if not mbj_gaps[i][1]:
                #     j, i = i, j
                data = {'comp_a': row.compositions[i], 
                        'comp_b': row.compositions[j],
                        'gap_a': mbj_gaps[i][0],
                        'gap_b': mbj_gaps[j][0],
                        'mp_id_a': row.mp_ids[i],
                        'mp_id_b': row.mp_ids[j],
                        'gap_direct_a':mbj_gaps[i][1],
                        'gap_direct_b': mbj_gaps[j][1],
                       }
                if data['comp_a'] == data['comp_b']:
                    continue
                combinations.append(data)

In [36]:
pairs = pd.DataFrame.from_dict(combinations)
#pairs = pairs[pairs.gap_direct_a | pairs.gap_direct_b]

In [37]:
pairs

,comp_a,comp_b,gap_a,gap_b,mp_id_a,mp_id_b,gap_direct_a,gap_direct_b
0,Ho(CuO2)2,Sm(CuO2)2,0.0000,0.6529,mp-9421,mp-9417,False,True
1,Ho(CuO2)2,Tm(CuO2)2,0.0000,0.7117,mp-9421,mp-754220,False,True
2,Ho(CuO2)2,(CuO2)(Y)(CuO2),0.0000,0.6934,mp-9421,mp-22618,False,True
3,Ho(CuO2)2,Gd(CuO2)2,0.0000,0.6799,mp-9421,mp-20707,False,True
4,Pr(CuO2)2,Sm(CuO2)2,0.0000,0.6529,mp-1101476,mp-9417,False,True
...,...,...,...,...,...,...,...,...
294,TbPtSb,TbPtBi,0.3806,0.0000,mp-16313,mp-1206989,True,False
295,YPtSb,YBiPt,0.4716,0.0000,mp-4964,mp-1206679,True,False
296,DyPtBi,DyPtSb,0.0000,0.3376,mp-30453,mp-16327,False,True
297,LiAlGe,LiInGe,0.4650,0.0000,mp-5920,mp-16343,False,False
298,PtSbS,PtSiSb,0.0000,0.3738,mp-1102850,mp-11152,False,False

In [39]:
 pairs[pairs.gap_direct_a | pairs.gap_direct_b]

,comp_a,comp_b,gap_a,gap_b,mp_id_a,mp_id_b,gap_direct_a,gap_direct_b
0,Ho(CuO2)2,Sm(CuO2)2,0.0000,0.6529,mp-9421,mp-9417,False,True
1,Ho(CuO2)2,Tm(CuO2)2,0.0000,0.7117,mp-9421,mp-754220,False,True
2,Ho(CuO2)2,(CuO2)(Y)(CuO2),0.0000,0.6934,mp-9421,mp-22618,False,True
3,Ho(CuO2)2,Gd(CuO2)2,0.0000,0.6799,mp-9421,mp-20707,False,True
4,Pr(CuO2)2,Sm(CuO2)2,0.0000,0.6529,mp-1101476,mp-9417,False,True
...,...,...,...,...,...,...,...,...
290,SrMgPb,CaSrPb,0.0000,0.6787,mp-1103314,mp-21166,False,True
291,BaMgSi,BaCaSi,0.0000,0.4676,mp-9934,mp-16253,False,True
294,TbPtSb,TbPtBi,0.3806,0.0000,mp-16313,mp-1206989,True,False
295,YPtSb,YBiPt,0.4716,0.0000,mp-4964,mp-1206679,True,False
296,DyPtBi,DyPtSb,0.0000,0.3376,mp-30453,mp-16327,False,True

In [26]:
pairs.to_csv('mbj_result_ternary_20250426.csv')